#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2019 OpenWrt.org

START=99
STOP=80

USE_PROCD=1

SPOA-BOUNCER_BIN="/usr/sbin/crowdsec-spoa-bouncer"
SPOA-BOUNCER_CONFIG="/etc/crowdsec/bouncer/crowdsec-spoa-bouncer.yaml"

start_service() {
        procd_open_instance
        procd_set_param respawn
        procd_set_param file "$SPOA-BOUNCER_CONFIG"
        procd_set_param reload_signal USR2
        procd_set_param command $SPOA-BOUNCER_BIN -c "$SPOA-BOUNCER_CONFIG"
        procd_close_instance
}

extra_command "check" "Check crowdsec-spoa-bouncer config"
check() {
        $SPOA-BOUNCER_BIN -t -v -c $SPOA-BOUNCER_CONFIG
}
